//Generated by ChatGPT
const subjects = [
	'The cat',
	'My friend',
	'A scientist',
	'The sun',
	'Our team',
	'The book',
];
const verbs = ['jumped', 'studied', 'built', 'sang', 'explored', 'discovered'];
const objects = [
	'the moon',
	'a new theory',
	'an adventure',
	'a song',
	'the ocean',
	'a treasure',
];

const randomNumber = (maxNum) => {
	return Math.floor(Math.random() * maxNum);
};

//make factory for future purposes, i.e. if we decide to add more parts to make more expanded sentences
const textFactory = (part1, part2, part3) => {
	return {
		part1,
		part2,
		part3,
	};
};

//making an output
const showText = (partsArray) => {
    let str = '';
    for (const part in partsArray) {        
        str += partsArray[part][randomNumber(partsArray[part].length)] + ' ';
    }
    str = str.substring(0, str.length - 1);
	return str + '.';
};

//call functions
const myWordsArray = textFactory(subjects, verbs, objects);
console.log(showText(myWordsArray));
